### ISSUE TITLE
Circular references in GraphQL schema

### ISSUE THREAD

**Issue by lonelyteapot** [Progyan1997/fastapi-clean-example#5]
How can we reference an `Author` in the `BookSchema` without producing circular import errors?
https://github.com/Progyan1997/fastapi-clean-example/blob/18a6772e461f7d75eb65e6af0ebd4baf5f82a2ed/schemas/graphql/Book.py#L3-L8

**Comment by Progyan1997** [comment]
Short answer is we can't. We can never know for sure with GraphQL that client won't re-enter same field key in the query causing infinite nesting. Hence, Circular Reference is off the limit.

**Comment by lonelyteapot** [comment]
This is not about the client though?
Circular references **in the schema** are normal and present in many APIs.
That kind of malicious behavior should be handled by query complexity
limiters.
The issue here is circular imports of python modules. If two classes are in
the same module, circular references work.
